### PR TITLE
SWEEP rate provider review

### LINKED ISSUE #15: SWEEP rate provider review
### Type of Smart Contract

Rate Provider

### Type of Smart Contract (if Other)

_No response_

### Contract Source Code

https://etherscan.io/address/0x9cE2837d6d84bb521A5a3002a2132B9E9E9cc4C8#code

### Additional Links

Same code in each case:

Arbitrum (main pegging venue): https://arbiscan.io/address/0x3bB6861c0Be6673809D55b9D346b6774B634a9D7
Optimism: https://optimistic.etherscan.io/address/0x33A48e4aA79A66fc4f7061f5D9E274528C213029
Avalanche: https://snowtrace.dev/address/0x709d075147a10495e5c3bBF3dfc0c138F34C6E72

### Protocol Documentation

https://docs.sweepr.finance

### Protocol Audits

https://github.com/SweeprFi/sweepr-contracts/tree/main/audits

### Terms and Conditions

- [X] The protocol to be integrated has been audited by at least one security firm or independent researcher.
- [X] If deployed, the contract is verified on etherscan.
- [X] The contract does not rely upon an EOA to supply any critical data (e.g., price).
- [X] If upgradeable, the contract's administrator is not an EOA.

### PR DESCRIPTION
**Pull request by mkflow27**
Fixes #15

Outstanding activities:

- [x] check findings
- [x] reread
- [x] peer review
- [x] add registry entries for all chain components
- [x] add summary judgement to review
- [x] add summary judgement to registry

### CODE REVIEW

**Review by danielmkm — CHANGES_REQUESTED** [review]
I'd agree with your assessment @mkflow27, some guardrails would make sene here.

**Comment by mkflow27** [comment]
Pasting the comment on issue here as well:

Since the sweep price relies on offchain components to supply price data, input validation especially zero checks help in preventing accidental missing inputs for example. This is not the case with the data the sweep oracle provides. Consider the following example:

1. [`getRate`](https://dashboard.tenderly.co/mcquardt/project/fork/cf74f7ad-e133-428e-aaa5-31d0ab726f28/simulation/9aea6bc0-7d7d-4b2c-9de0-c6a25e3cb780) returns `1021805000000000000`
2. The offchain system calls `setTargetePrice(0,0)` without input validation. [Simulation](https://dashboard.tenderly.co/mcquardt/project/fork/cf74f7ad-e133-428e-aaa5-31d0ab726f28/simulation/bc0aec3a-b758-4827-9939-5000800b75ca)
3. Reading the rate again returns `0`. [Simulation](https://dashboard.tenderly.co/mcquardt/project/fork/cf74f7ad-e133-428e-aaa5-31d0ab726f28/simulation/ceb851b6-96dd-42e7-b085-16f8fd0ba8c7)

**Comment by mkflow27** [comment]
@danielmkm The contracts were upgraded and include input validation such as:
- zero input checks
- threshold variation checks

I have marked the reviewed rate providers as safe.

**Review by danielmkm — APPROVED** [review]
Great work @mkflow27!

**Pull request merged**
