### PR TITLE
Affine Rate Providers (2)

### LINKED ISSUE #149: Affine Rate Providers (2)
### Type of Smart Contract

Rate Provider

### Type of Smart Contract (if Other)

_No response_

### Contract Source Code

https://etherscan.io/address/0x4E4C0ea425bacc68cD2Acbf1cdaa234bE9Dd8742

### Additional Links

https://etherscan.io/address/0x3e47F17725628Fde5330C2310B799545ef40C93e

### Protocol Documentation

https://docs.affinedefi.com/

### Protocol Audits

https://docs.affinedefi.com/security/audit-reports

### Terms and Conditions

- [X] The protocol to be integrated has been audited by at least one security firm or independent researcher.
- [X] If deployed, the contract & all involved downstream contracts are verified on etherscan.
- [X] The contract does not rely upon an EOA to supply any critical data (e.g., price).
- [X] If upgradeable, the contract's administrator is not an EOA.

### PR DESCRIPTION
**Pull request by mkflow27**
Fixes #149

### CODE REVIEW

**Comment by mkflow27** [comment]
@Zen-Maxi Can you ask about the proposer and/or executor roles on their timelock controller. Currently both are EOAs. Would be good if you can confirm with them.

**Comment by maruf0011** [comment]
@mkflow27 
On our timelock controller only multisig has propose role. executor is address(0), so anyone can execute proposal after passing multisig. 

1. timelock: https://etherscan.io/address/0x4B21438ffff0f0B938aD64cD44B8c6ebB78ba56e
2. multisig: https://etherscan.io/address/0x67Ec3Bb25a5DB6eB7Ba74f6C0b2bA193A3983FB8

**Comment by mkflow27** [comment]
@maruf0011 Thanks for the clarification.

**Review by danielmkm — APPROVED** [review]
Looks good, thanks @mkflow27

**Pull request merged**
