### PR TITLE
eBTC Rate Provider

### LINKED ISSUE #134: eBTC Rate Provider
### Type of Smart Contract

Rate Provider

### Type of Smart Contract (if Other)

_No response_

### Contract Source Code

https://etherscan.io/address/0x81be3526a71d9013a1a5bd38758e0f248231b523#readContract

### Additional Links

_No response_

### Protocol Documentation

https://etherfi.gitbook.io/etherfi/liquid/ebtc-bitcoin-lrt-vault

### Protocol Audits

https://github.com/Se7en-Seas/boring-vault/tree/main/audit

### Terms and Conditions

- [X] The protocol to be integrated has been audited by at least one security firm or independent researcher.
- [X] If deployed, the contract & all involved downstream contracts are verified on etherscan.
- [X] The contract does not rely upon an EOA to supply any critical data (e.g., price).
- [X] If upgradeable, the contract's administrator is not an EOA.

### PR DESCRIPTION
**Pull request by mkflow27**
Fixes #134

Outstanding activities:

Outstanding activities:

- [ ] summary
- [ ] peer review

### CODE REVIEW

**Comment by mkflow27** [comment]
@Zen-Maxi Similar question as in the weETHs pr here: https://github.com/balancer/code-review/pull/94/files#diff-094145a04738e17e78f688615c745a3c99c80cc944fa47b274ad928bdcd68f39R93

Ideally the rateProvider utilises `getRateSafe` to check if the system is paused (due to a wrong price data being pushed)

**Comment by mkflow27** [comment]
@Zen-Maxi Could you verify with the team the following observation.

Based on this txHash 0xb21d447fbaa73159d20cc2ecc508e224cdd66e41378601001af09308f3df16c0 It is indicated that Role "11" is allowed to call `function updateExchangeRate(uint96 newExchangeRate) external requiresAuth` on the contract with address "0xcB762D7bedfA78c725f2F347220d41062b6B0A4A" Indicated by the event "RoleCapabilityUpdated".

```
// ["event RoleCapabilityUpdated(uint8 indexed role, address indexed target, bytes4 indexed functionSig, bool enabled)"]
txHash 0xb21d447fbaa73159d20cc2ecc508e224cdd66e41378601001af09308f3df16c0
Result(4) [
  11n,
  '0xcB762D7bedfA78c725f2F347220d41062b6B0A4A',
  '0x3458113d',
  true
]
```

if I investigate which accounts have been given which role by looking at all `UserRoleUpdated` events. I see that no account has been given role "11". Meaning, currently no account is allowed to call `updateExchangeRate`.

**Comment by danielmkm** [comment]
Will hold off on the review here until we get an update.

**Comment by crispymangoes** [comment]
> @Zen-Maxi Similar question as in the weETHs pr here: https://github.com/balancer/code-review/pull/94/files#diff-094145a04738e17e78f688615c745a3c99c80cc944fa47b274ad928bdcd68f39R93 #94
> 
> Ideally the rateProvider utilises `getRateSafe` to check if the system is paused (due to a wrong price data being pushed)

Yes I think using `getRateSafe()` is a good idea, just noting that when the Accountant is paused, swapping would revert as calls to get the rate would revert.

**Comment by crispymangoes** [comment]
> @Zen-Maxi Could you verify with the team the following observation.
> 
> Based on this txHash 0xb21d447fbaa73159d20cc2ecc508e224cdd66e41378601001af09308f3df16c0 It is indicated that Role "11" is allowed to call `function updateExchangeRate(uint96 newExchangeRate) external requiresAuth` on the contract with address "0xcB762D7bedfA78c725f2F347220d41062b6B0A4A" Indicated by the event "RoleCapabilityUpdated".
> 
> ```
> // ["event RoleCapabilityUpdated(uint8 indexed role, address indexed target, bytes4 indexed functionSig, bool enabled)"]
> txHash 0xb21d447fbaa73159d20cc2ecc508e224cdd66e41378601001af09308f3df16c0
> Result(4) [
>   11n,
>   '0xcB762D7bedfA78c725f2F347220d41062b6B0A4A',
>   '0x3458113d',
>   true
> ]
> ```
> 
> if I investigate which accounts have been given which role by looking at all `UserRoleUpdated` events. I see that no account has been given role "11". Meaning, currently no account is allowed to call `updateExchangeRate`.

The UPDATE_EXCHANGE_RATE_ROLE is currently granted to eth:0x41DFc53B13932a2690C9790527C1967d8579a6ae and eth:0x71E2d6c34f569cC4Df5802d675B208FB8AE3Bcd6. Though for the mean time this would only be used for emergencies. In the future when eigen layer is emitting rewards the exchange rate is likely to increase though.

**Comment by Zen-Maxi** [comment]
For context the adapted rate provider is: https://etherscan.io/address/0xdDDF909076B641C51f22ACD4b134C54adad51e68#code and was deployed from the respective factory: https://etherscan.io/address/0x467665d4ae90e7a99c9c9af785791058426d6ea0#code

**Review by danielmkm — APPROVED** [review]
Looks good, thanks mkflow

**Pull request merged**
