### PR TITLE
Updating registry

### PR DESCRIPTION
**Pull request by Zen-Maxi**

### CODE REVIEW

**Comment by Zen-Maxi** [comment]
Based on this sheet, did not add any from Fantom or below 500 USD TVL. https://docs.google.com/spreadsheets/d/1I7OsWcO__6B73Nsuukb3DErnDa5IjjKEaWwqAQiMVuE/edit#gid=0

Some rate providers are actually totally wrong and unsafe. Maybe better we dont make a habit of adding those; so new users cannot use or see them. Other option would be add every rate provider ever even if unsafe or wrong; to me that sounds bloated.

**Comment by mkflow27** [comment]
@Zen-Maxi I think unsafe rate providers should not ever be added to this registry. Only scenario I see to have an unsafe Rate Provider in here is if it was previously safe and a change in circumstances made it unsafe.

**Comment by franzns** [comment]
We should not add wrong ones.

How the API/UI will handle this is that all on this list would be flagged as a warning and the UI would disable deposit actions on the pool

**Comment by franzns** [comment]
> @Zen-Maxi I think unsafe rate providers should not ever be added to this registry. Only scenario I see to have an unsafe Rate Provider in here is if it was previously safe and a change in circumstances made it unsafe. 

Isnt that the case for the reth rateprovider on arb?

**Comment by mkflow27** [comment]
@franzns afaik this is the case for the reth on arbitrum, yes. So adding it as part of this pr is fine. However I think the jAURA and Bitfrost ones never were used really. Let's wait for @Zen-Maxi to clarify.

**Comment by Zen-Maxi** [comment]
I would rather not include the unsafe rate providers unless they went from safe to unsafe like you guys have signalled above. As for the unused / old ones it may be best to leave them out entirely. A handful of fixes and recent Chainlink additions are in this PR but removing the ones that were never safe is also fine by me if we all agree.

**Comment by mkflow27** [comment]
@Zen-Maxi Sure, if you could remove all the unsafe rateProviders that were not "safe" once and resolve conflicts I will review.

**Comment by franzns** [comment]
Sounds good to me!

**Review by mkflow27 — APPROVED** [review]
Thanks @Zen-Maxi

**Pull request merged**
